after-ssafy-dj-2nd/Online-Test

BackEnd/bin/.gitignore, BackEnd/src/main/java/com/onlinetest/backend/BackendApplication.java, BackEnd/src/main/java/com/onlinetest/backend/controller/ProblemController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/ProblemDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Agency.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Problem.java, BackEnd/src/main/java/com/onlinetest/backend/service/IProblemService.java, BackEnd/src/main/java/com/onlinetest/backend/service/ProblemServiceImpl.java, BackEnd/src/main/resources/application.properties, BackEnd/src/main/resources/mybatis-config.xml, BackEnd/src/main/resources/problem.xml
1. 소속 기관
- 소속기관 추가
<p>
</p>
</details>
=> [BE-002] 소속기관 추가

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/App.js, FrontEnd/src/assets/css/default.css, FrontEnd/src/components/Common/Footer.css, FrontEnd/src/components/Common/Footer.js, FrontEnd/src/components/Common/Header.css, FrontEnd/src/components/Common/Header.js, FrontEnd/src/index.js, FrontEnd/src/pages/IntroPage.js, FrontEnd/src/pages/LoginPage.js, FrontEnd/src/pages/NotFoundPage.js, FrontEnd/src/pages/SignupPage.js, FrontEnd/src/pages/TeacherPage.js, FrontEnd/src/pages/TestPage.js
1. React Router 적용
- ` App.js`에 `Switch`와 `Route`를 이용해서 URL 주소별로 component 다르게 보이도록 기본적인 설정
- `components` 에 컴포넌트를 만든 후 `pages`의 각 Page에 만든 컴포넌트를 가져와서 배치할 수 있도록 구성
2. `Header` 컴포넌트에 `Link` 적용
3. `NotFoundPage` 컴포넌트 구성
- 지정하지 않은 URL 주소로 접근시 해당 페이지가 없다는 안내 문구 보이도록 구성
- 메인 페이지로 이동할 수 있는 링크 구성
<p>
</p>
</details>
=> [FE-003] 리액트 라우터 적용

BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/User.java, BackEnd/src/main/java/com/onlinetest/backend/service/IUserService.java, BackEnd/src/main/java/com/onlinetest/backend/service/UserServiceImpl.java, BackEnd/src/main/resources/mybatis-config.xml, BackEnd/src/main/resources/user.xml
1. 회원가입
> User 클래스 생성
> signUp 기능 추가
2. id 체크
> 회원가입 시 필요한 id 체크 기능 추가
<p>
</p>
</details>
=> [BE-003] 회원가입 추가

BackEnd/.gitignore, BackEnd/src/main/java/com/onlinetest/backend/controller/ProblemController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/ProblemDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Problem.java, BackEnd/src/main/java/com/onlinetest/backend/service/IProblemService.java, BackEnd/src/main/java/com/onlinetest/backend/service/ProblemServiceImpl.java, BackEnd/src/main/resources/application.properties, BackEnd/src/main/resources/problem.xml
1. problems(get)
> 문제 전체 보기
2. problem(get, post, put, delete)
> 문제 CRUD
- 전체적으로 유저 권한에 무관하게 진행이 됩니다.
- Problems가 제대로 작동하지 않습니다. -> sql이 잘못 되었습니다.....ㅠ 그리고 resulttype을 명시하지 않았슴다..
=> [BE-004] 문제 CRUD controller, interface, service, dao, mapper, dto 작성

BackEnd/.gitignore, BackEnd/src/main/java/com/onlinetest/backend/controller/ProblemController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/ProblemDaoImpl.java, BackEnd/src/main/resources/application.properties, BackEnd/src/main/resources/problem.xml
1. 출력내용 확인
2. POST, PUT 확인 루직 구축
=> [BE-004] 컨트롤러 로직 변경

BackEnd/build.gradle, BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/UserSwagger.java, BackEnd/src/main/resources/application.properties
1. swagger 적용
> UserController에만 우선 적용
2. dto.swagger 패키지
> swagger에서 편하게 model 보기 위해 생성
<p>
</p>
</details>
=> [BE-008] swagger 적용

.github/CODEOWNERS, FrontEnd/src/App.js, FrontEnd/src/components/Common/Header.js, FrontEnd/src/components/Teacher/TeacherChart.js, FrontEnd/src/components/Teacher/TeacherExam.js, FrontEnd/src/components/Teacher/TeacherHome.js, FrontEnd/src/components/Teacher/TeacherNavBar.js, FrontEnd/src/components/Teacher/TeacherStudent.js, FrontEnd/src/components/Teacher/teacher.css, FrontEnd/src/pages/TeacherPage.js, FrontEnd/src/util/DOM.js
1. Route 적용
2. 왼쪽 Navbar를 이용하여teacher / home, student, exam, chart 로 이동 가능
3. 각 페이지 switch 로 분기
- css 미적용
- 각 페이지 content 비어있음
- path 값을 const로 활용하여 재 커밋할 예정
<p>
</p>
</details>
=> FE-026] Route 이용, teacher 기본페이지와 전환

.gitignore, BackEnd/Dockerfile, FrontEnd/dockerfile, FrontEnd/nginx.conf, docker-compose.yml
1. Docker File 작성
> Front용 도커파일 작성
> Front용 nginx.conf setting 파일 작성
> Back용 도커파일 작성
2. Docker Compose 작성
> Docker File 작동을 위한 Docker-compose.yml 파일 작성
=> [BE-007] Docker, Docker-Compose 파일 작성

docker-compose.yml
1. 로그인
> 로그인 함수 수정
2. 로그인 레이아웃
> 버튼 레이아웃 수정
<p>
</p>
</details>
=> docker-compose 파일 위치 정리

FrontEnd/src/App.js, FrontEnd/src/components/Intro/IntroContent.css, FrontEnd/src/components/Intro/IntroContent.js, FrontEnd/src/components/Intro/IntroDefault.css, FrontEnd/src/components/Intro/Welcome.css, FrontEnd/src/components/Intro/Welcome.js, FrontEnd/src/index.js, FrontEnd/src/pages/IntroPage.js
1. 로그인
> 로그인 함수 수정
2. 로그인 레이아웃
> 버튼 레이아웃 수정
<p>
</p>
</details>
* `Welcome` 컨포넌트와 `IntroContent` 컨포넌트로 나눔.
* `Welcom` 컨포넌트
* 서비스 이름, 간략한 소개 글, 서비스를 표현할 수 있는 이미지로 구성
* `IntroContent` 컨포넌트
* 서비스 이용 방법에 대해 소개
* 다른 콘텐츠에 대해서도 생각 중입니다...
* 승십이형 방법으로 해결쓰
* `IntroPage` 내부 컨포넌트  `self-closing tag`로 바꿨습니다.
=> [FE-012] IntroPage 기본 레이아웃 설정, IntroPage 내부 콘텐츠 레이아웃 설정, IntroPage에서 Header, Footer 제거

FrontEnd/src/components/Teacher/TeacherExam.js, FrontEnd/src/components/Teacher/TeacherNavBar.js, FrontEnd/src/components/Teacher/teacher.css, FrontEnd/src/pages/TeacherPage.js
1.  useState , useReducer를 이용하여 exam 생성 페이지 구현
2. 입력값 에러 부분 처리
3.  백엔드 api와 연결하는 로직 미구현
- input type 중 datatime-local 이 요새 많이 사용되지 않는 type이라 date, time 으로 따로 표기를 해야될지 고민
- #root .show 같은 css의 경우 default css로 변경 필요
<p>
</p>
</details>
=> [FE-029] exam 생성 페이지

FrontEnd/src/components/Teacher/TeacherQuestion.js, FrontEnd/src/components/Teacher/TeacherQuestionList.js
1. question 구현 레이아웃
2. questionList 에서 question 으로 데이터와 setquestion 전달후 아래에서 questionList의 setquestions 작동시키는 방식
<p>
</p>
</details>
=> [FE-031] question 생성 레이아웃

BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dto/User.java, BackEnd/src/main/resources/user.xml
1. User
> agency_id 제거
> name, emali 추가
2. 로그인, 회원가입
> 바뀐 객체에 맞게 수정
<p>
</p>
</details>
=> [BE-003] 회원가입, 로그인 수정

FrontEnd/src/components/Teacher/TeacherExam.js, FrontEnd/src/components/Teacher/TeacherQuestion.js, FrontEnd/src/components/Teacher/TeacherQuestionList.js, FrontEnd/src/components/Teacher/teacher.css
1. example 로직 backend 와 통일
2. default css 로 분리한 부분 제거
<p>
</p>
</details>
=> [FE-029] example 로직 변경, default css분리작업

BackEnd/src/main/java/com/onlinetest/backend/controller/QuestionController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Exam.java, BackEnd/src/main/java/com/onlinetest/backend/dto/ExamStudent.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Question.java, BackEnd/src/main/java/com/onlinetest/backend/dto/QuestionExam.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/QuestionList.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/resources/mybatis-config.xml, BackEnd/src/main/resources/test.xml
1. 시험 응시 시작
> ready test에서는 시험 정보 리턴
> start test에서는 해당 시험에 포함된 문제 리스트 리턴
2. Question
> question의 type을 boolean으로 변경
<p>
</p>
</details>
=> [BE-010] 시험 응시 시작

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/assets/css/normalize.css, FrontEnd/src/components/Common/Modal.css, FrontEnd/src/components/Common/Modal.js, FrontEnd/src/components/Login/FindPassword.css, FrontEnd/src/components/Login/FindPassword.js, FrontEnd/src/components/Login/Login.css, FrontEnd/src/components/Login/Login.js, FrontEnd/src/components/Login/Signup.css, FrontEnd/src/components/Login/Signup.js
- `Common` 폴더 안에 `Modal.js`로 공통 컴포넌트 구성
- 자세한 사용법은 아래에 작성해놓음
- 부드럽게 Modal을 열고 닫히는 효과를 주기 위해 react 전용 transition library인 `react-addons-css-transition-group`을 설치함 (merge된 후 pull 받고난 다음에 `npm install` 명령어 한 번 입력해서 라이브러리 설치해주세요 🙏 )
- `Login.js` 컴포넌트 하단에 모달 만드는 방법 예시 작성해놓음
- 개선할 부분이나 추가적인 의견 있으면 공유해요~
- 각 컴포넌트마다 자유롭게 스타일링하기 위해 제거함
=> [FE-006] Modal 컴포넌트 구성

FrontEnd/src/components/Teacher/TeacherHome.js, FrontEnd/src/components/Teacher/TeacherNavBar.js, FrontEnd/src/components/Teacher/exam.js, FrontEnd/src/components/Teacher/examcard.js, FrontEnd/src/components/Teacher/teacher.css, FrontEnd/src/util/time.js
1. BE 연결 로직 없음 - EXAM_SAMPLE 이용하여 구성
2.  util/time.js 로 시간을 통하여 시작 시간, 종료시간을 이용하여 시험 진행 시간과 현재 시험 상태값 출력
3. 변수명 정리
* start, end -> startSec, endSec
* lockIcon -> lockIconClass
* stringToTime -> timeToString
- api 로직과 연결필요
<p>
</p>
</details>
=> [FE-027] 홈화면에 시험 list 표기

BackEnd/src/main/java/com/onlinetest/backend/controller/QuestionController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java
1. CORS 모든 헤더와 모든 origin에 대해 Allow 설정 하였습니다.
* question controller
* test controller
* user controller
<p>
</p>
</details>
=> [BE-016] CORS 모두 허용 설정

BackEnd/build.gradle, BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java, BackEnd/src/main/java/com/onlinetest/backend/controller/QuestionController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/JwtInterceptor.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/UnauthorizedException.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/WebConfig.java, BackEnd/src/main/java/com/onlinetest/backend/service/IJwtService.java, BackEnd/src/main/java/com/onlinetest/backend/service/JwtServiceImpl.java
1. jwt 추가
> 로그인 시 토큰 생성하여 header에 담아 보냄
> jwtservice.getId()를 통해 id값 가져올 수 있음
> 로그인, 회원가입 기능 외에는 토큰이 있어야 접근할 수 있음(필요시 수정 가능)
2. swagger
> 테스트용으로 모든 기능마다 2번 유저의 토큰 정보 디폴트 세팅
3. 자동 재시작 (gradle 추가)
> spring boot 수정하면 자동 재시작하도록 설정
<p>
</p>
</details>
=> [BE-014] JWT 추가

FrontEnd/src/components/Intro/IntroContent.js, FrontEnd/src/components/Intro/Welcome.js
=> [FE-013] 인트로페이지 버튼 클릭시 이벤트 추가

BackEnd/src/main/java/com/onlinetest/backend/interceptor/JwtInterceptor.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/UnauthorizedException.java
1. preflight 이슈
> options 메소드 호출시 true
2. 토큰 인증 에러 수정
> 500 -> 401 에러
<p>
</p>
</details>
=> [BE-017] preflight 이슈 해결

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/api/config/interceptors.js, FrontEnd/src/api/index.js, FrontEnd/src/api/modules/exams.js, FrontEnd/src/api/modules/questions.js, FrontEnd/src/api/modules/user.js, FrontEnd/src/components/Common/Modal.js, FrontEnd/src/components/Login/FindPassword.js, FrontEnd/src/components/Login/Login.js, FrontEnd/src/components/Login/Signup.css, FrontEnd/src/components/Login/Signup.js, FrontEnd/src/util/validation.js
- `api` 폴더 안에 `axios` 기본 세팅과 기능별로 `modules` 폴더 안에 api 구성할 수 있도록 세팅
- 필요한 API를 구성하고 싶을 때 `modules` 폴더 안에 해당 기능에 맞는 파일에서 작성하면 됨
- 백엔드로 `token` 값을 보내야 하는 경우 `api` > `config` > `interceptors.js`에서 `request` 부분에 구현되어 있음
- 지금은 임시로 `.env.local` 파일에 `REACT_APP_TEMP_TOKEN=*****` 형태로 작성 후 임시 토큰 값을 불러와서 구현되었지만 추후 `redux`를 통해서 로그인 하면 `jwt`를 decode한 후 해당 `token` 값을 `interceptors.js`에 불러와서 구현할 예정
- `pull` 받은 후 각자 `FrontEnd` 폴더 바로 아래에 `.env.local` 파일 만든 후 `REACT_APP_TEMP_TOKEN=*****` 와 같이 작성하고 저장 후 `npm run start`로 로컬 서버 실행할 것(`*****` 부분은 현재 임시로 만들어진 토큰 값 작성하면 됨)
- **`merge` 된 후 `pull` 받은 후 `npm i` 명령어로 `axios` library 먼저 설치 후 작업 시작할 것**
- `Login.js`와 `Signup.js`에 로그인, 회원가입하는 로직 작성
- `async`, `await` 구문으로 비동기 로직을 구성하고 `try`, `catch` …
=> [FE-016] 로그인, 회원가입 버튼 동작 구현

BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java, BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Example.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Question.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/JwtServiceImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/resources/test.xml
1. 토큰 유효기간 설정
> 현재는 24시간으로 설정
2. 시험 시작
> question에 example 추가
> 수정된 dto에 맞게 수정 (QuestionExample 제거, resultMap 사용)
> 시험 시작 시 이전에 응시한 이력 체크
<p>
</p>
</details>
=> [BE-010] 시험 응시 이력 체크 및 example 추가

BackEnd/build.gradle, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/IUserService.java, BackEnd/src/main/java/com/onlinetest/backend/service/UserServiceImpl.java, BackEnd/src/main/resources/user.xml
1. 메일 전송
> Gmail SMTP를 사용하여 메일 전송
<p>
</p>
</details>
=> [BE-018] 임시 비밀번호 메일 전송

BackEnd/build.gradle, BackEnd/src/main/java/com/onlinetest/backend/controller/ExamController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/QuestionController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/QuestionDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Example.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Question.java, BackEnd/src/main/java/com/onlinetest/backend/service/IQuestionService.java, BackEnd/src/main/java/com/onlinetest/backend/service/QuestionServiceImpl.java, BackEnd/src/main/resources/question.xml, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/QuestionControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/daoTest/QuestionDaoTest.java, FrontEnd/dockerfile
1. build.gradle 수정
> 401 Error 확인을 위한 httpclient 추가
> test code 작동을 위한 테스트 컴파일 추가
2. Question Controller 변경
> 보기가 들어오지 않으면 400 Error 나오도록 변경
> 문제 리스트로 입력할 수 있는 api 작성
3. Question Service 변경
> 문제 리스트가 들어오고 나갈 때 형식 dto로 따로 작성
4. question sql 변경
> 특정 문제 받아오는 부분에서 누락된 유저 검증 추가
5. Question Dao, Controller Test 추가
> QuestionDao에 있는 기능 검증
> QuestionController에 있는 기능 검증
<p>
</p>
</details>
=> [BE-019] Question Test Code 작성

BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Answer.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Submit.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/SubmitSwagger.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/resources/test.xml
1. 응시종료
> 채점
> answer테이블에 답 기록 (복수답안의 경우 ',' 붙여서 String으로 기록)
> 응시 종료 시각과 점수 기록
<p>
</p>
</details>
=> [BE-012] 시험응시종료 기록 및 채점

BackEnd/src/main/java/com/onlinetest/backend/controller/ExamController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/Exam.java, BackEnd/src/main/java/com/onlinetest/backend/dto/QuestionExam.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/ExamQuestionsSwagger.java, BackEnd/src/main/resources/exam.xml, BackEnd/src/main/resources/user.xml, BackEnd/src/test/java/com/onlinetest/backend/BackendApplicationTests.java, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/ExamControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/QuestionControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/daoTest/ExamDaoTest.java, BackEnd/src/test/java/com/onlinetest/backend/daoTest/QuestionDaoTest.java
1. 시간 확인 api 구성(User Controller)
> 서버 시간을 보내주는 api 구성
2. Exam Dao Test 코드 작성 및 오류 사항 수정
> 각 dao 작동 여부 확인 및 오류 사항 수정
3. Exam Controller Test 코드 작성 및 오류 사항 수정
> 버튼 레이아웃 수정
</p>
</details>
=> [BE-020] Exam Dao, Controller 테스트 코드 작성

BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/resources/test.xml
1. 시험 응시 시작 조건 추가
> 시험 응시할 수 있는 시간인지 확인
<p>
</p>
</details>
=> [BE-021] 응시 조건 추가

FrontEnd/package-lock.json, FrontEnd/package.json
- `xlsx` 라는 새로운 라이브러리가 추가되고 branch 병합되면서 `comma`가 사라지는 현상이 발생해서 `package.json` 올바르게 수정
=> [Hotfix - 002] Frontend package.json 수정

BackEnd/src/main/java/com/onlinetest/backend/controller/ExamController.java
초기에 시험을 만들때 문제가 없이도 생성이 가능하도록 수정
1. 시험 컨트롤러 수정
문제가 없어도 시험 생성 가능하도록 수정
<p>
</p>
</details>
=> [Hotfix - 001] 시험 컨트롤러 fix

BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/QuestionList.java
1. Exam Dto 변수명 변경
> 문제 여러개 넣는 Api Question -> Questions로 변경
<p>
</p>
</details>
=> [Hotfix-003] 문제 여러개 받는부분 변수명 변경

BackEnd/src/main/java/com/onlinetest/backend/interceptor/WebConfig.java, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/UserControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/daoTest/UserDaoTest.java
1. 인터셉터 예외사항 업데이트
> 비밀 번호 찾는 부분 예외 처리
2. 유저 컨트롤러 테스팅
> 유저 컨트롤러 테스팅
3. 유저 Dao 테스팅
> Dao 테스팅
<p>
</p>
</details>
=> [BE-023] User 테스트 코드 작성

FrontEnd/src/api/config/interceptors.js, FrontEnd/src/components/Login/Login.js
1. login 할때 sessionStorage 와 redux 에 토큰 저장
axios 요청할때 저장된 해당 token 을 이용해서 headers 에 token 추가해주는 작업
<p>
</p>
</details>
=> FE-035] login 시 token 정보 저장 및 axios header 에 token보내기

FrontEnd/src/api/modules/exams.js, FrontEnd/src/api/modules/questions.js, FrontEnd/src/components/Question.js, FrontEnd/src/components/Teacher/exam/ExamAddQuestion.js, FrontEnd/src/components/Teacher/exam/TeacherExam.js, FrontEnd/src/components/Teacher/exam/TeacherExamDetail.js, FrontEnd/src/components/Teacher/home/TeacherHome.js, FrontEnd/src/components/Teacher/home/exam.js, FrontEnd/src/components/Teacher/questions/TeacherQuestionList.js, FrontEnd/src/components/Teacher/questions/TeacherQuestionListAdd.js, FrontEnd/src/components/Teacher/teacher.css, FrontEnd/src/pages/TeacherPage.js
1. exam 에 question 추가 및 제거
2. exam 생성한것 제거
3. question 제거
4. 백엔드와 변수명 다른것 동기화
<p>
</p>
</details>
=> FE-036] Exam, Question 정리

BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java, BackEnd/src/main/java/com/onlinetest/backend/controller/ExamController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/User.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/QuestionList.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/WebConfig.java, BackEnd/src/main/java/com/onlinetest/backend/service/IUserService.java, BackEnd/src/main/java/com/onlinetest/backend/service/JwtServiceImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/UserServiceImpl.java, BackEnd/src/main/resources/user.xml, BackEnd/src/test/java/com/onlinetest/backend/BackendApplicationTests.java, FrontEnd/nginx.conf
1. User의 유저 아이디 제거
> User의 유저 아이디 제거
<p>
</p>
</details>
=> [Hotfix-005] User의 유저 아이디 제거

BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dto/User.java, BackEnd/src/main/resources/user.xml, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/ExamControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/UserControllerTest.java, BackEnd/src/test/java/com/onlinetest/backend/daoTest/UserDaoTest.java
1. User DAO, Controller 테스팅
> User DAO, Controller 테스트 완료
<p>
</p>
</details>
=> [Hotfix-005] User DAO, Controller 테스트 완료

BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/ExamUserResultSwagger.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/ExamUserSwagger.java, BackEnd/src/main/java/com/onlinetest/backend/service/IMailService.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/IUserService.java, BackEnd/src/main/java/com/onlinetest/backend/service/MailServiceImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/UserServiceImpl.java, BackEnd/src/main/resources/test.xml, BackEnd/src/main/resources/user.xml
1. 선생님이 학생 이메일을 보내줄때 있는지 없는지 판단하는 부분 작성
있는 사람이면 registeredStudent에 위치하고 없는 사람이면 notFoundedStudent에 위치함
2. 있는 사람(registeredStudent)에 위치한 사람에 대해 메일링 서비스 진행
mailservice를 통해 메일 전송
<p>
</p>
</details>
=> [BE-024] 메일 보내는 부분 업데이트

BackEnd/src/main/java/com/onlinetest/backend/SwaggerConfig.java
1. URL 수정
>  swagger-ui.html -> api/swagger-ui.html
<p>
</p>
</details>
=> [BE-028] swagger URL 수정

BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/UserDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/User.java, BackEnd/src/main/java/com/onlinetest/backend/interceptor/WebConfig.java, BackEnd/src/main/java/com/onlinetest/backend/service/AES256ServiceImpl.java, BackEnd/src/main/java/com/onlinetest/backend/service/IAES256Service.java, BackEnd/src/main/java/com/onlinetest/backend/service/IUserService.java, BackEnd/src/main/java/com/onlinetest/backend/service/UserServiceImpl.java, BackEnd/src/main/resources/user.xml, BackEnd/src/test/java/com/onlinetest/backend/controllerTest/UserControllerTest.java
1. 메일 인증 구성
> 암호화 서비스 구성
> 메일 서비스를 이용해 메일 발송
<p>
</p>
</details>
=> [BE-026] 회원 인증 메일 구성

BackEnd/src/main/java/com/onlinetest/backend/controller/TestController.java, BackEnd/src/main/java/com/onlinetest/backend/controller/UserController.java, BackEnd/src/main/java/com/onlinetest/backend/dao/TestDaoImpl.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/ExamReadySwagger.java, BackEnd/src/main/java/com/onlinetest/backend/dto/swagger/ExamStartSwagger.java, BackEnd/src/main/java/com/onlinetest/backend/service/ITestService.java, BackEnd/src/main/java/com/onlinetest/backend/service/TestServiceImpl.java, BackEnd/src/main/resources/test.xml
1. 시험 준비(readytest)
- status 메시지 추가
- 존재하지 않는 시험 NOT_FOUND로 수정
2. 시험 시작(starttest)
- status 메시지 추가
- setStarTest : 기존 insert에서 업데이트(starttime)하도록 수정
<p>
</p>
</details>
=> [BE-027] 시험 준비,시작 수정

FrontEnd/src/components/Login/Login.js, FrontEnd/src/components/Login/Signup.js, FrontEnd/src/pages/TeacherPage.js
1. 로그인 및 회원 가입 id => email로 수정
2. teacher page 리다이렉트 로직 수정
- 리덕스에서 유저정보를 가져오지 않고 세션에서 가져오도록 변경
<p>
</p>
</details>
=> [Hotfix-006] 로그인 및 회원가입 id를 이메일로 수정, teacher page 리다이렉트 로직 수정

FrontEnd/src/api/index.js
1. FrontEnd base Url 
baseUrl ->  https://untacttest.ga/api/ 으로 변경
<p>
</p>
</details>
=> [Hotfix FE-004] FrontEnd baseUrl 변경
